/**
 * Markdown Renderer
 *
 * Renders diagnostic and doctor results as GitHub-Flavoured Markdown (GFM).
 *
 * What this teaches:
 * - How structured data maps to document formats
 * - GFM table syntax and badge conventions
 * - Why having a renderer abstraction lets you support new formats without
 *   touching any command logic
 *
 * Architecture note:
 * Lives in the CLI layer. No external dependencies — pure string generation.
 */

import type { ReportRenderer } from '../../core/reporting/report-renderer.js';
import type { DiagnosticResult, DiagnosticCheck } from '../../core/types/diagnostic.js';
import type { DoctorResult } from '../../core/types/doctor-result.js';
import type { CheckStatus } from '../../core/types/diagnostic.js';

// ── Helpers ───────────────────────────────────────────────────────

const STATUS_EMOJI: Record<CheckStatus, string> = {
  pass: '✅',
  warn: '⚠️',
  fail: '❌',
  skip: '⏭️',
};

const STATUS_LABEL: Record<CheckStatus, string> = {
  pass: 'Pass',
  warn: 'Warn',
  fail: 'Fail',
  skip: 'Skip',
};

function statusCell(status: CheckStatus): string {
  return `${STATUS_EMOJI[status]} ${STATUS_LABEL[status]}`;
}

function formatTimestamp(date: Date): string {
  // Use ISO 8601 format for saved reports — consistent across all locales,
  // timezones, and machines. Terminal display uses locale formatting; file
  // output uses the unambiguous ISO string.
  if (!(date instanceof Date)) return String(date);
  return date.toISOString();
}

function renderCheck(check: DiagnosticCheck): string {
  const lines: string[] = [];

  lines.push(`#### ${STATUS_EMOJI[check.status]} ${check.label}`);
  lines.push('');
  lines.push(`**Status:** ${STATUS_LABEL[check.status]}  `);
  lines.push(`**Message:** ${check.message}`);

  if (check.detail) {
    lines.push('');
    lines.push('<details>');
    lines.push('<summary>Detail</summary>');
    lines.push('');
    lines.push(check.detail);
    lines.push('</details>');
  }

  if (check.suggestion) {
    lines.push('');
    lines.push(`> 💡 **Suggestion:** ${check.suggestion}`);
  }

  return lines.join('\n');
}

// ── Renderer ──────────────────────────────────────────────────────

export class MarkdownRenderer implements ReportRenderer {
  renderDiagnostic(result: DiagnosticResult): string {
    const lines: string[] = [];

    lines.push(`# ${result.displayName} Diagnostics`);
    lines.push('');
    lines.push(
      `> Generated by **Dev Doctor** · ${formatTimestamp(result.timestamp)} · ${result.durationMs}ms`,
    );
    lines.push('');

    // Summary table
    const passCount = result.checks.filter((c) => c.status === 'pass').length;
    const warnCount = result.checks.filter((c) => c.status === 'warn').length;
    const failCount = result.checks.filter((c) => c.status === 'fail').length;

    lines.push('## Summary');
    lines.push('');
    lines.push(`| Overall | Checks | Passed | Warnings | Failed |`);
    lines.push(`|---------|--------|--------|----------|--------|`);
    lines.push(
      `| ${statusCell(result.overallStatus)} | ${result.checks.length} | ${passCount} | ${warnCount} | ${failCount} |`,
    );
    lines.push('');

    // Check details
    lines.push('## Checks');
    lines.push('');

    // Quick-glance table
    lines.push('| Check | Status | Message |');
    lines.push('|-------|--------|---------|');
    for (const check of result.checks) {
      const msg = check.message.replace(/\|/g, '\\|');
      lines.push(`| ${check.label} | ${statusCell(check.status)} | ${msg} |`);
    }
    lines.push('');

    // Detailed section for non-passing checks
    const nonPassing = result.checks.filter((c) => c.status !== 'pass');
    if (nonPassing.length > 0) {
      lines.push('## Issues & Recommendations');
      lines.push('');
      for (const check of nonPassing) {
        lines.push(renderCheck(check));
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  renderDoctor(result: DoctorResult): string {
    const lines: string[] = [];

    lines.push('# Dev Doctor — Health Report');
    lines.push('');
    lines.push(`> Generated · ${formatTimestamp(result.timestamp)} · ${result.durationMs}ms`);
    lines.push('');

    // Health score
    lines.push('## Health Score');
    lines.push('');
    const healthEmoji =
      result.health.status === 'healthy' ? '💚' : result.health.status === 'degraded' ? '💛' : '❤️';

    lines.push(
      `**${healthEmoji} ${result.health.status.charAt(0).toUpperCase() + result.health.status.slice(1)}** — ${result.health.percentage}%`,
    );
    lines.push('');
    lines.push(`| Passed | Warnings | Failed | Total |`);
    lines.push(`|--------|----------|--------|-------|`);
    lines.push(
      `| ${result.health.passedChecks} | ${result.health.warningChecks} | ${result.health.failedChecks} | ${result.health.totalChecks} |`,
    );
    lines.push('');

    // Plugin diagnostics
    if (result.diagnostics.length > 0) {
      lines.push('## Plugin Diagnostics');
      lines.push('');
      lines.push('| Plugin | Status | Checks | Duration |');
      lines.push('|--------|--------|--------|----------|');
      for (const diag of result.diagnostics) {
        lines.push(
          `| ${diag.displayName} | ${statusCell(diag.overallStatus)} | ${diag.checks.length} | ${diag.durationMs}ms |`,
        );
      }
      lines.push('');

      // Per-plugin failing checks
      const withIssues = result.diagnostics.filter((d) => d.overallStatus !== 'pass');
      if (withIssues.length > 0) {
        lines.push('## Issues');
        lines.push('');
        for (const diag of withIssues) {
          lines.push(`### ${diag.displayName}`);
          lines.push('');
          for (const check of diag.checks.filter((c) => c.status !== 'pass')) {
            lines.push(renderCheck(check));
            lines.push('');
          }
        }
      }
    }

    // Detected tools
    if (result.tools.length > 0) {
      lines.push('## Development Tools');
      lines.push('');
      lines.push('| Tool | Status | Version |');
      lines.push('|------|--------|---------|');
      for (const tool of result.tools) {
        const badge = tool.installed ? '✅ Installed' : '⏭️ Not found';
        const version = tool.version ? `v${tool.version}` : '—';
        lines.push(`| ${tool.name} | ${badge} | ${version} |`);
      }
      lines.push('');
    }

    return lines.join('\n');
  }
}
